---

# tasks file for install redis-cluster
- block: #Block for RedHat
    - name: install redhat
      yum:
        name: redis
        state: latest

     

  when: ansible_os_family == "RedHat"
- block: #Block for Debian
    - name: install apache for ubuntu 
      apt:
        name: redis
        state: latest
  when: ansible_os_family == "Debian"
# - name: copy config file
#   template: 
#     src: "templetes/{{ item }}"
#     dest: "/etc/redis/{{ item }}"
#   with_fileglob: 
#       - "redis_master.conf.j2" 
#       - "redis_slave.conf.j2"
- name: copy config file master
  template: 
    src: "redis_master.conf.j2"
    dest: "{{ destin_folder }}/redis_master.conf"
- name: copy config file slave
  template: 
    src: "redis_slave.conf.j2"
    dest: "{{ destin_folder }}/redis_slave.conf"
- name: start redis
  shell:
    cmd: "redis-server {{ item }}"
  with_items:
    - /etc/redis/redis_master.conf
    - /etc/redis/redis_slave.conf
- name: start cluster
 # debug: "redis-cli --cluster create {{ hostvars[groups['all'][0]].ansible_host }}:6379 {{ hostvars[groups['all'][0]].ansible_host }}:6381 {{ hostvars[groups['all'][0]].ansible_host }}:6380 {{ hostvars[groups['all'][0]].ansible_host }}:6379 {{ hostvars[groups['all'][0]].ansible_host }}:6380 {{ hostvars[groups['all'][0]].ansible_host }}:6381 --cluster-replicas 1"
  shell: 
    cmd: "redis-cli --cluster create {{ hostvars[groups['all'][0]].ansible_host }}:7001 {{ hostvars[groups['all'][0]].ansible_host }}:7002 {{ hostvars[groups['all'][0]].ansible_host }}:7001 {{ hostvars[groups['all'][0]].ansible_host }}:7002 {{ hostvars[groups['all'][0]].ansible_host }}:7001 {{ hostvars[groups['all'][0]].ansible_host }}:7002 --cluster-replicas 1"
  when: inventory_hostname in groups['master']

