---
#tasks file for install redis-cluster
- block: #Block for RedHat
    - name: install redhat
      shell: "yum --enablerepo=remi install redis"       
  when: ansible_os_family == "RedHat"
# - name: install redis
#   apt: 
#     name: redis
#     state: latest
#     update_cache: yes
# - name: install sentinel
#   apt: 
#     name: redis-sentinel
#     state: latest
#     update_cache: yes
- block: #block for master
  - name: copy config file redis master
    template: 
      src: "redis-master-sentinel.conf.j2"
      dest: "/etc/redis-sentinel.conf"
  - name: copy config file slave
    template: 
      src: "redis-master.conf.j2"
      dest: "/etc/redis-master.conf"
  - name: start redis
    shell:
      cmd: "redis-server /etc/redis-master.conf & redis-sentinel /etc/redis-sentinel.conf"
  when: inventory_hostname in groups["master"]
- block: #block for slave
  - name: copy config file redis slave
    template: 
      src: "redis-sentinel-slave.conf.j2"
      dest: "/etc/redis-sentinel.conf"
  - name: copy config file slave
    template: 
      src: "redis-slave.conf.j2"
      dest: "/etc/redis-slave.conf"
  - name: start redis
    shell:
      cmd: "redis-server /etc/redis-slave.conf & redis-sentinel /etc/redis-sentinel.conf"
  when: inventory_hostname in groups['slave']
- name: instsall haproxy 
  yum: 
    name: haproxy
    state: latest
- name: copy haproxy conf 
  template: 
    src: "redis-sentinel-slave.conf.j2"
    dest: "/etc/redis-sentinel.conf"
- name: start haproxy
  service:
    name: haproxy
    httpdstate: started


